masterdb:
  image: percona:5.6
  ports:
    - "3307:3306"
  volumes:
    - ./masterdb/cnf:/etc/mysql/conf.d
    - ./masterdb/data:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: mypass
    DB_NAME: testreplicate
    REPLICATION_MODE: master
    REPLICATION_USER: relp
    REPLICATION_PASS: pass
    REPLICATION_SSLMODE:

slavedb:
  image: percona:5.6
  ports:
    - "3308:3306"
  links:
    - masterdb:mysql
  volumes:
    - ./slavedb/cnf:/etc/mysql/conf.d
    - ./slavedb/data:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: mypass
    REPLICATION_MODE: slave
    REPLICATION_HOST: master
    REPLICATION_USER: relp
    REPLICATION_PASS: pass
